### ISSUE TITLE
After running docker-compose up the CGI server cannot connect to master

### ISSUE THREAD

**Issue by niebardzo** [katharostech/docker_lizardfs#2]
After running docker-compose up the CGI server cannot connect to master. It seems that the port 9421 is not exposed to the host.

**Comment by zicklag** [comment]
Hmm, that's strange. The port doesn't need to be exposed to the host because all of the services in the `docker-compose.yaml` will get implicitly placed on the same docker network. That means that the CGI server will be on the same network as the `mfsmaster` and will have access to all of the ports on that container without them having been exposed individually.

I'll *probably* have the chance to try it out today or tomorrow to investigate.

**Comment by zicklag** [comment]
OK, figured it out. You have to put the master host in the URL when accessing the web UI. I updated the [README](https://github.com/katharostech/docker_lizardfs#cgi-server) to be more explicit about that.

    http://192.168.99.100:8080/mfs.cgi?masterhost=mfsmaster

**Comment by niebardzo** [comment]
Ok, it works fine now. Thanks a lot.

**Comment by zicklag** [comment]
No problem. Glad it worked. :smiley:

**Comment by zicklag** [comment]
@niebardzo I just pushed an update to the container that allows you to set the `MASTER_HOST` and `MASTER_PORT` environment variables on the CGI server so that you don't have to put the host and port in the URL.

That might help make that experience nicer in some circumstances.
